import colorsys
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import sqlite3
import os

# Define Project Root (3 levels up from backend/modules/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH = os.path.join(PROJECT_ROOT, "database", "evidence.db")
REPORT_DIR = os.path.join(PROJECT_ROOT, "reports")

def create_pdf(case_id):
    os.makedirs(REPORT_DIR, exist_ok=True)
    
    # Sanitize case_id for filename use
    safe_case_id = case_id.replace("\\", "_").replace("/", "_").replace(":", "")
    pdf_path = os.path.join(REPORT_DIR, f"PRISM7_Report_{safe_case_id}.pdf")

    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(colors.HexColor("#3498db"))  # Forensic Blue
    c.drawString(50, height - 50, f"PRISM7 Sovereign Report: {case_id}")

    # Section: Evidence Metadata
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.HexColor("#2c3e50"))  # Accent Dark
    c.drawString(50, height - 100, "Evidence Metadata:")

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Query 1: Metadata
    cursor.execute("SELECT filename, hash, timestamp FROM evidence WHERE case_id=?", (case_id,))
    rows = cursor.fetchall()

    y = height - 120
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    for r in rows:
        c.drawString(60, y, f"FILE: {r[0]} | HASH: {r[1]} | TIMESTAMP: {r[2]}")
        y -= 20

    # Section: Threat Intelligence (Audit from Vault/Chain)
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.HexColor("#c0392b")) # Threat Red
    c.drawString(50, y - 20, "Threat Intelligence & Risk Assessment:")
    y -= 40
    
    # Query: Filter for Intelligence events
    cursor.execute("SELECT timestamp, action, evidence_id FROM chain_of_custody WHERE case_id=? AND notes LIKE 'BC_TX: INTEL_ANALYSIS%' ORDER BY timestamp DESC LIMIT 5", (case_id,))
    intel_rows = cursor.fetchall()
    
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.black)
    if not intel_rows:
        c.drawString(60, y, "◈ NO_INTEL_ANALYSIS_PERFORMED_ON_THIS_CASE")
        y -= 20
    else:
        for ir in intel_rows:
            c.drawString(60, y, f"◈ {ir[0][:19]} | {ir[1]} | {ir[2]}")
            y -= 15

    # Section: Timeline
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.HexColor("#2c3e50"))
    c.drawString(50, y - 20, "Chain of Custody (On-Chain Verified):")
    y -= 40
    
    # Query 2: Vault
    cursor.execute("SELECT timestamp, action, operator FROM chain_of_custody WHERE case_id=? ORDER BY timestamp ASC", (case_id,))
    vault_rows = cursor.fetchall()
    conn.close()
    
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.black)
    for vr in vault_rows:
        c.drawString(60, y, f"◈ {vr[0][:19]} | {vr[1]} | OP: {vr[2]}")
        y -= 15
        if y < 50:
            c.showPage()
            y = height - 50

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.HexColor("#7f8c8d"))  # Slate Gray
    c.drawString(50, 30, "Generated by PRISM7 // The Sovereign Forensic Suite")

    c.save()
    return pdf_path